add need and error handling

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -18,13 +18,21 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - id: step1
+        name: "Read Version String and write to output"
         run: |
           project_version=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
+          # fail, if version is not a valid version string (mvn outputs "null object or invalid expression")
+          if [[ "$project_version" = "null object or invalid expression" ]]; then
+              echo "Could not determine project version. Output was: $project_version"
+              echo "Aborting"
+              exit 1
+          fi
           echo "${project_version}"
           echo "project_version=${project_version}" >> "$GITHUB_OUTPUT"
 
   build:
     name: Build to test
+    needs: read-version-string
     uses: ./.github/workflows/build.yml
     with:
       version: ${{ needs.read-version-string.outputs.project_version }}
